insert into product (product_id, categoryprod_id, name, price, availible_count, discount) values (1, 104, 'Snoutbean', 4108.82, 32, null);
insert into product (product_id, categoryprod_id, name, price, availible_count, discount) values (2, 4, 'Broadleaf Milkweed', 2251.67, 84, null);
insert into product (product_id, categoryprod_id, name, price, availible_count, discount) values (3, 79, 'Datura', 3677.99, 43, 15);
insert into product (product_id, categoryprod_id, name, price, availible_count, discount) values (4, 40, 'Pride-of-rochester', 4102.63, 48, null);
insert into product (product_id, categoryprod_id, name, price, availible_count, discount) values (5, 61, 'Centerville Brazos-mint', 1915.69, 4, null);
insert into product (product_id, categoryprod_id, name, price, availible_count, discount) values (6, 76, 'Yerba Neto Hoja De Cueva', 2178.73, 82, null);
insert into product (product_id, categoryprod_id, name, price, availible_count, discount) values (7, 21, 'Pacific Bentgrass', 1017.86, 57, 15);
insert into product (product_id, categoryprod_id, name, price, availible_count, discount) values (8, 29, 'Indian Headdress', 1514.12, 9, null);
insert into product (product_id, categoryprod_id, name, price, availible_count, discount) values (9, 39, 'Manyseed Goosefoot', 3343.74, 100, 15);
insert into product (product_id, categoryprod_id, name, price, availible_count, discount) values (10, 73, 'Sticky Chinese Houses', 4437.4, 65, null);
insert into product (product_id, categoryprod_id, name, price, availible_count, discount) values (11, 40, 'Indian Walnut', 1640.52, 49, null);
insert into product (product_id, categoryprod_id, name, price, availible_count, discount) values (12, 76, 'Longleaf Bush Lupine', 4231.65, 80, null);
insert into product (product_id, categoryprod_id, name, price, availible_count, discount) values (13, 18, 'Canistel', 3316.36, 27, null);
insert into product (product_id, categoryprod_id, name, price, availible_count, discount) values (14, 19, 'Scouler''s Woollyweed', 3321.54, 57, null);
insert into product (product_id, categoryprod_id, name, price, availible_count, discount) values (15, 30, 'Vreeland''s Coralroot', 4676.17, 37, null);
insert into product (product_id, categoryprod_id, name, price, availible_count, discount) values (16, 23, 'Desert Snowberry', 1210.0, 96, null);
insert into product (product_id, categoryprod_id, name, price, availible_count, discount) values (17, 35, 'San Bernardino Beardtongue', 2814.12, 68, 15);
insert into product (product_id, categoryprod_id, name, price, availible_count, discount) values (18, 18, 'Dwarf Arctic Ragwort', 620.92, 46, 15);
insert into product (product_id, categoryprod_id, name, price, availible_count, discount) values (19, 105, 'Chautle Livingrock', 2264.39, 52, 15);
insert into product (product_id, categoryprod_id, name, price, availible_count, discount) values (20, 32, 'Thatching Grass', 198.53, 33, null);
insert into product (product_id, categoryprod_id, name, price, availible_count, discount) values (21, 24, 'Waxy Thoroughwort', 2139.95, 1, 15);
insert into product (product_id, categoryprod_id, name, price, availible_count, discount) values (22, 24, 'Wreath Lichen', 1686.94, 75, null);
insert into product (product_id, categoryprod_id, name, price, availible_count, discount) values (23, 103, 'Eastern Mojave Buckwheat', 2930.57, 85, null);
insert into product (product_id, categoryprod_id, name, price, availible_count, discount) values (24, 77, 'Rusty Popcornflower', 2385.65, 61, null);
insert into product (product_id, categoryprod_id, name, price, availible_count, discount) values (25, 72, 'Hybrid Violet', 4441.14, 100, null);
insert into product (product_id, categoryprod_id, name, price, availible_count, discount) values (26, 103, 'Harsh Indian Paintbrush', 1197.63, 86, 15);
insert into product (product_id, categoryprod_id, name, price, availible_count, discount) values (27, 96, 'Hybrid Rock Polypody', 4276.64, 62, 15);
insert into product (product_id, categoryprod_id, name, price, availible_count, discount) values (28, 47, 'Rock-loving Sandwort', 1299.41, 96, null);
insert into product (product_id, categoryprod_id, name, price, availible_count, discount) values (29, 99, 'Spindleroot', 3399.07, 75, null);
insert into product (product_id, categoryprod_id, name, price, availible_count, discount) values (30, 62, 'Newberry''s Lipfern', 3777.49, 78, 15);
insert into product (product_id, categoryprod_id, name, price, availible_count, discount) values (31, 36, 'Sierra Currant', 4475.76, 99, null);
insert into product (product_id, categoryprod_id, name, price, availible_count, discount) values (32, 40, 'Painted Milkvetch', 3570.62, 68, null);
insert into product (product_id, categoryprod_id, name, price, availible_count, discount) values (33, 40, 'Christmas Cherry', 2729.06, 81, 15);
insert into product (product_id, categoryprod_id, name, price, availible_count, discount) values (34, 60, 'Kjellman''s Groundsel', 2317.44, 30, null);
insert into product (product_id, categoryprod_id, name, price, availible_count, discount) values (35, 104, 'Kauai Clermontia', 1549.93, 91, 15);
insert into product (product_id, categoryprod_id, name, price, availible_count, discount) values (36, 73, 'Mcdougall''s Yellowtops', 941.87, 48, null);
insert into product (product_id, categoryprod_id, name, price, availible_count, discount) values (37, 73, 'Longstyle Thistle', 4930.62, 5, null);
insert into product (product_id, categoryprod_id, name, price, availible_count, discount) values (38, 33, 'Kamapua''a', 1885.43, 32, 15);
insert into product (product_id, categoryprod_id, name, price, availible_count, discount) values (39, 56, 'Shortstyle Indian Paintbrush', 4307.06, 99, null);
insert into product (product_id, categoryprod_id, name, price, availible_count, discount) values (40, 57, 'Lecidea Lichen', 3089.38, 17, null);
insert into product (product_id, categoryprod_id, name, price, availible_count, discount) values (41, 105, 'Polytrichum Moss', 4588.34, 9, null);
insert into product (product_id, categoryprod_id, name, price, availible_count, discount) values (42, 85, 'Slender Flatsedge', 3314.01, 63, 15);
insert into product (product_id, categoryprod_id, name, price, availible_count, discount) values (43, 76, 'Fescue Airplant', 3228.49, 85, null);
insert into product (product_id, categoryprod_id, name, price, availible_count, discount) values (44, 21, 'Meadow Geranium', 2739.31, 79, 15);
insert into product (product_id, categoryprod_id, name, price, availible_count, discount) values (45, 22, 'Lewisia', 929.11, 30, null);
insert into product (product_id, categoryprod_id, name, price, availible_count, discount) values (46, 66, 'Whitecolumn Foxtail Cactus', 1638.99, 64, null);
insert into product (product_id, categoryprod_id, name, price, availible_count, discount) values (47, 77, 'Spreading Hedgeparsley', 1486.91, 41, null);
insert into product (product_id, categoryprod_id, name, price, availible_count, discount) values (48, 20, 'False Horkelia', 1435.52, 86, 15);
insert into product (product_id, categoryprod_id, name, price, availible_count, discount) values (49, 79, 'Cloudcroft Phacelia', 4136.48, 18, 15);
insert into product (product_id, categoryprod_id, name, price, availible_count, discount) values (50, 60, 'Rose Campion', 915.62, 84, null);
insert into product (product_id, categoryprod_id, name, price, availible_count, discount) values (51, 29, 'Carolina False Vervain', 4538.27, 95, null);
insert into product (product_id, categoryprod_id, name, price, availible_count, discount) values (52, 50, 'Trailing Abutilon', 279.66, 91, null);
insert into product (product_id, categoryprod_id, name, price, availible_count, discount) values (53, 101, 'Koolau Range Melicope', 967.96, 8, null);
insert into product (product_id, categoryprod_id, name, price, availible_count, discount) values (54, 14, 'Atrichum Moss', 1391.05, 12, 15);
insert into product (product_id, categoryprod_id, name, price, availible_count, discount) values (55, 9, 'Lettuce Wirelettuce', 3175.1, 96, null);
insert into product (product_id, categoryprod_id, name, price, availible_count, discount) values (56, 56, 'Riverbank Sedge', 877.66, 72, null);
insert into product (product_id, categoryprod_id, name, price, availible_count, discount) values (57, 34, 'Giant Shield Lichen', 1546.15, 25, null);
insert into product (product_id, categoryprod_id, name, price, availible_count, discount) values (58, 37, 'Aladdin''s Slippers', 1399.72, 67, null);
insert into product (product_id, categoryprod_id, name, price, availible_count, discount) values (59, 21, 'Tuber Anemone', 1676.0, 78, null);
insert into product (product_id, categoryprod_id, name, price, availible_count, discount) values (60, 82, 'Silvery Sedge', 1881.31, 45, null);
insert into product (product_id, categoryprod_id, name, price, availible_count, discount) values (61, 18, 'French Flax', 3764.84, 32, null);
insert into product (product_id, categoryprod_id, name, price, availible_count, discount) values (62, 18, 'Texas Greasebush', 1059.43, 54, null);
insert into product (product_id, categoryprod_id, name, price, availible_count, discount) values (63, 53, 'Hogwort', 1899.29, 86, 15);
insert into product (product_id, categoryprod_id, name, price, availible_count, discount) values (64, 84, 'Hawkweed', 3051.18, 18, null);
insert into product (product_id, categoryprod_id, name, price, availible_count, discount) values (65, 60, 'Bessey''s Stickseed', 1080.44, 73, null);
insert into product (product_id, categoryprod_id, name, price, availible_count, discount) values (66, 82, 'Todsen''s False Pennyroyal', 559.05, 34, null);
insert into product (product_id, categoryprod_id, name, price, availible_count, discount) values (67, 45, 'Richardson''s Brookfoam', 4086.28, 36, 15);
insert into product (product_id, categoryprod_id, name, price, availible_count, discount) values (68, 104, 'Dustseed', 1985.55, 42, null);
insert into product (product_id, categoryprod_id, name, price, availible_count, discount) values (69, 77, 'Apache Pass Spiderling', 4893.19, 21, null);
insert into product (product_id, categoryprod_id, name, price, availible_count, discount) values (70, 96, 'Mexican Orange', 676.04, 55, null);
insert into product (product_id, categoryprod_id, name, price, availible_count, discount) values (71, 104, 'Terrestrial Water-starwort', 2900.75, 10, null);
insert into product (product_id, categoryprod_id, name, price, availible_count, discount) values (72, 31, 'Pachira', 4142.45, 56, null);
insert into product (product_id, categoryprod_id, name, price, availible_count, discount) values (73, 21, 'Daisy Desertstar', 4106.95, 91, null);
insert into product (product_id, categoryprod_id, name, price, availible_count, discount) values (74, 42, 'Azure Bluet', 1128.46, 73, 15);
insert into product (product_id, categoryprod_id, name, price, availible_count, discount) values (75, 32, 'Slender Pinepink', 4551.41, 98, null);
insert into product (product_id, categoryprod_id, name, price, availible_count, discount) values (76, 12, 'Point Reyes Bentgrass', 2635.22, 75, null);
insert into product (product_id, categoryprod_id, name, price, availible_count, discount) values (77, 99, 'Dewey Sedge', 3630.02, 64, 15);
insert into product (product_id, categoryprod_id, name, price, availible_count, discount) values (78, 20, 'Spreading Alkaliweed', 2694.27, 7, 15);
insert into product (product_id, categoryprod_id, name, price, availible_count, discount) values (79, 19, 'Abert''s Creeping Zinnia', 2968.34, 26, null);
insert into product (product_id, categoryprod_id, name, price, availible_count, discount) values (80, 108, 'Spiked False Mannagrass', 4475.12, 34, null);
insert into product (product_id, categoryprod_id, name, price, availible_count, discount) values (81, 79, 'Schadonia Lichen', 4425.13, 4, null);
insert into product (product_id, categoryprod_id, name, price, availible_count, discount) values (82, 67, 'Thistle Cholla', 797.23, 24, null);
insert into product (product_id, categoryprod_id, name, price, availible_count, discount) values (83, 53, 'Orphniospora Lichen', 1665.11, 95, 15);
insert into product (product_id, categoryprod_id, name, price, availible_count, discount) values (84, 80, 'Roundleaf Sundew', 2221.39, 8, null);
insert into product (product_id, categoryprod_id, name, price, availible_count, discount) values (85, 106, 'Lady''s Tresses', 474.43, 37, null);
insert into product (product_id, categoryprod_id, name, price, availible_count, discount) values (86, 103, 'Endococcus Lichen', 3691.43, 67, null);
insert into product (product_id, categoryprod_id, name, price, availible_count, discount) values (87, 37, 'Hoffmann''s Buckwheat', 2871.07, 38, null);
insert into product (product_id, categoryprod_id, name, price, availible_count, discount) values (88, 90, 'Feltleaf Willow', 4362.92, 2, null);
insert into product (product_id, categoryprod_id, name, price, availible_count, discount) values (89, 84, 'Coneplant', 3216.49, 56, null);
insert into product (product_id, categoryprod_id, name, price, availible_count, discount) values (90, 44, 'Boreal Locoweed', 3213.54, 69, 15);
insert into product (product_id, categoryprod_id, name, price, availible_count, discount) values (91, 27, 'Mustang Clover', 3292.27, 49, null);
insert into product (product_id, categoryprod_id, name, price, availible_count, discount) values (92, 4, 'Pussy Willow', 2206.99, 77, 15);
insert into product (product_id, categoryprod_id, name, price, availible_count, discount) values (93, 2, 'Schlegelia', 2550.5, 11, null);
insert into product (product_id, categoryprod_id, name, price, availible_count, discount) values (94, 79, 'Isothecium Moss', 1978.75, 18, null);
insert into product (product_id, categoryprod_id, name, price, availible_count, discount) values (95, 104, 'Konocti Manzanita', 1322.55, 13, null);
insert into product (product_id, categoryprod_id, name, price, availible_count, discount) values (96, 66, 'Smallbristle Hound''s Tongue', 1257.62, 67, null);
insert into product (product_id, categoryprod_id, name, price, availible_count, discount) values (97, 76, 'Prickly Spiderflower', 4439.74, 30, null);
insert into product (product_id, categoryprod_id, name, price, availible_count, discount) values (98, 29, 'Palm Fern', 911.21, 29, 15);
insert into product (product_id, categoryprod_id, name, price, availible_count, discount) values (99, 108, 'Mule Mountain Brickellbush', 1031.46, 62, 15);
insert into product (product_id, categoryprod_id, name, price, availible_count, discount) values (100, 4, 'Plantainleaf Buttercup', 4478.47, 23, null);
insert into product (product_id, categoryprod_id, name, price, availible_count, discount) values (101, 61, 'Rocky Mountain Fescue', 4945.05, 13, null);
insert into product (product_id, categoryprod_id, name, price, availible_count, discount) values (102, 14, 'Anacolia Moss', 3452.35, 36, 15);
insert into product (product_id, categoryprod_id, name, price, availible_count, discount) values (103, 83, 'Guiana Plum', 679.84, 89, 15);
insert into product (product_id, categoryprod_id, name, price, availible_count, discount) values (104, 100, 'Fen Grass Of Parnassus', 501.92, 60, 15);
insert into product (product_id, categoryprod_id, name, price, availible_count, discount) values (105, 17, 'Funaria Moss', 2963.53, 55, 15);
insert into product (product_id, categoryprod_id, name, price, availible_count, discount) values (106, 32, 'Hairy Cyanea', 1986.05, 66, null);
insert into product (product_id, categoryprod_id, name, price, availible_count, discount) values (107, 18, 'Rim Lichen', 146.12, 47, 15);
insert into product (product_id, categoryprod_id, name, price, availible_count, discount) values (108, 47, 'Burk''s Smooth Rockcress', 2738.21, 82, 15);
insert into product (product_id, categoryprod_id, name, price, availible_count, discount) values (109, 86, 'Siskiyou Fleabane', 2922.63, 71, null);
insert into product (product_id, categoryprod_id, name, price, availible_count, discount) values (110, 98, 'Cutleaf Teasel', 1217.91, 72, null);
insert into product (product_id, categoryprod_id, name, price, availible_count, discount) values (111, 63, 'Haleakala Catchfly', 3100.6, 12, null);
insert into product (product_id, categoryprod_id, name, price, availible_count, discount) values (112, 104, 'Iwatsukiella Moss', 1189.5, 2, 15);
insert into product (product_id, categoryprod_id, name, price, availible_count, discount) values (113, 47, 'Ertter''s Ragwort', 3828.51, 87, null);
insert into product (product_id, categoryprod_id, name, price, availible_count, discount) values (114, 21, 'Mediterranean Medick', 3144.86, 30, 15);
insert into product (product_id, categoryprod_id, name, price, availible_count, discount) values (115, 11, 'Grassflower', 236.37, 57, null);
insert into product (product_id, categoryprod_id, name, price, availible_count, discount) values (116, 15, 'Pinescrub Bluestem', 1447.83, 68, null);
insert into product (product_id, categoryprod_id, name, price, availible_count, discount) values (117, 30, 'Lyreleaf Jewelflower', 2907.43, 6, null);
insert into product (product_id, categoryprod_id, name, price, availible_count, discount) values (118, 37, 'Garden Lovage', 3536.11, 71, 15);
insert into product (product_id, categoryprod_id, name, price, availible_count, discount) values (119, 93, 'Andreaea Moss', 1178.66, 63, null);
insert into product (product_id, categoryprod_id, name, price, availible_count, discount) values (120, 72, 'Flaxleaf Monardella', 135.69, 59, null);
insert into product (product_id, categoryprod_id, name, price, availible_count, discount) values (121, 101, 'Arizona Spinystar', 3065.59, 96, 15);
insert into product (product_id, categoryprod_id, name, price, availible_count, discount) values (122, 22, 'Wirestem Buckwheat', 3098.52, 58, null);
insert into product (product_id, categoryprod_id, name, price, availible_count, discount) values (123, 77, 'Boxfruit Alani', 4891.17, 89, null);
insert into product (product_id, categoryprod_id, name, price, availible_count, discount) values (124, 100, 'Antilles Tonguefern', 1711.0, 31, null);
insert into product (product_id, categoryprod_id, name, price, availible_count, discount) values (125, 101, 'Piper''s Fleabane', 4356.65, 20, 15);
insert into product (product_id, categoryprod_id, name, price, availible_count, discount) values (126, 9, 'Nuttall''s Meadowbeauty', 2699.33, 66, null);
insert into product (product_id, categoryprod_id, name, price, availible_count, discount) values (127, 27, 'Rock Sea-lavender', 1175.13, 93, null);
insert into product (product_id, categoryprod_id, name, price, availible_count, discount) values (128, 14, 'Windmill Fringed Gentian', 2270.41, 72, null);
insert into product (product_id, categoryprod_id, name, price, availible_count, discount) values (129, 2, 'Devil''s Darning Needles', 4351.26, 15, null);
insert into product (product_id, categoryprod_id, name, price, availible_count, discount) values (130, 31, 'Mountain Marsh Larkspur', 1250.68, 95, null);
insert into product (product_id, categoryprod_id, name, price, availible_count, discount) values (131, 13, 'Fall Tansyaster', 4750.0, 71, null);
insert into product (product_id, categoryprod_id, name, price, availible_count, discount) values (132, 50, 'Virginia Jointvetch', 1018.58, 40, null);
insert into product (product_id, categoryprod_id, name, price, availible_count, discount) values (133, 28, 'Jagleaf Junglefern', 3678.92, 98, 15);
insert into product (product_id, categoryprod_id, name, price, availible_count, discount) values (134, 17, 'San Saba Pinweed', 1825.9, 10, 15);
insert into product (product_id, categoryprod_id, name, price, availible_count, discount) values (135, 109, 'Spokane False Goldenaster', 4952.27, 73, null);
insert into product (product_id, categoryprod_id, name, price, availible_count, discount) values (136, 18, 'Castrate Carpetgrass', 832.46, 95, 15);
insert into product (product_id, categoryprod_id, name, price, availible_count, discount) values (137, 33, 'Warnock''s Prairie Clover', 1147.89, 62, null);
insert into product (product_id, categoryprod_id, name, price, availible_count, discount) values (138, 87, 'Squirting Cucumber', 3602.82, 94, null);
insert into product (product_id, categoryprod_id, name, price, availible_count, discount) values (139, 81, 'Bessey''s Locoweed', 1025.78, 9, null);
insert into product (product_id, categoryprod_id, name, price, availible_count, discount) values (140, 48, 'Geyer''s Biscuitroot', 4850.91, 45, null);
insert into product (product_id, categoryprod_id, name, price, availible_count, discount) values (141, 45, 'Rough Strongbark', 4448.44, 7, null);
insert into product (product_id, categoryprod_id, name, price, availible_count, discount) values (142, 92, 'Japanese Iris', 1651.39, 10, null);
insert into product (product_id, categoryprod_id, name, price, availible_count, discount) values (143, 51, 'Acuteleaf Dicranum Moss', 3293.81, 13, null);
insert into product (product_id, categoryprod_id, name, price, availible_count, discount) values (144, 25, 'Maraca Montuna', 2584.31, 95, 15);
insert into product (product_id, categoryprod_id, name, price, availible_count, discount) values (145, 17, 'Cold-desert Phlox', 1151.34, 47, null);
insert into product (product_id, categoryprod_id, name, price, availible_count, discount) values (146, 23, 'Caribbean Seagrass', 3404.76, 10, null);
insert into product (product_id, categoryprod_id, name, price, availible_count, discount) values (147, 34, 'Sargent Juniper', 1888.22, 6, 15);
insert into product (product_id, categoryprod_id, name, price, availible_count, discount) values (148, 84, 'Tapellaria Lichen', 1101.05, 15, null);
insert into product (product_id, categoryprod_id, name, price, availible_count, discount) values (149, 106, 'Great Valley Phacelia', 4581.04, 16, null);
insert into product (product_id, categoryprod_id, name, price, availible_count, discount) values (150, 69, 'Whiteleaf Leather Flower', 4524.12, 86, 15);
insert into product (product_id, categoryprod_id, name, price, availible_count, discount) values (151, 63, 'Hardy Fuchsia', 1010.23, 18, 15);
insert into product (product_id, categoryprod_id, name, price, availible_count, discount) values (152, 61, 'Heermann''s Buckwheat', 137.44, 18, null);
insert into product (product_id, categoryprod_id, name, price, availible_count, discount) values (153, 42, 'Navajo Yucca', 1850.16, 47, null);
insert into product (product_id, categoryprod_id, name, price, availible_count, discount) values (154, 44, 'Georgia Rockcress', 4652.3, 73, null);
insert into product (product_id, categoryprod_id, name, price, availible_count, discount) values (155, 59, 'Twocolor Monkshood', 1932.67, 70, null);
insert into product (product_id, categoryprod_id, name, price, availible_count, discount) values (156, 44, 'Pacific Silverweed', 1969.8, 32, 15);
insert into product (product_id, categoryprod_id, name, price, availible_count, discount) values (157, 106, 'Arctic Wart Lichen', 3233.63, 8, 15);
insert into product (product_id, categoryprod_id, name, price, availible_count, discount) values (158, 101, 'Ibapah Tickweed', 2461.8, 19, 15);
insert into product (product_id, categoryprod_id, name, price, availible_count, discount) values (159, 71, 'Cynodontium Moss', 3627.63, 8, 15);
insert into product (product_id, categoryprod_id, name, price, availible_count, discount) values (160, 71, 'Bladder Pod', 2612.52, 53, 15);
insert into product (product_id, categoryprod_id, name, price, availible_count, discount) values (161, 10, 'Mexican Copperleaf', 4760.67, 37, null);
insert into product (product_id, categoryprod_id, name, price, availible_count, discount) values (162, 74, 'Cartilage Lichen', 3874.3, 81, null);
insert into product (product_id, categoryprod_id, name, price, availible_count, discount) values (163, 108, 'Yellow Wall Bedstraw', 2198.46, 7, null);
insert into product (product_id, categoryprod_id, name, price, availible_count, discount) values (164, 45, 'Pulvinate Chalice Lichen', 1083.64, 31, 15);
insert into product (product_id, categoryprod_id, name, price, availible_count, discount) values (165, 79, 'British Soldier Lichen', 453.14, 78, null);
insert into product (product_id, categoryprod_id, name, price, availible_count, discount) values (166, 73, 'Chaparral Dodder', 2922.21, 7, null);
insert into product (product_id, categoryprod_id, name, price, availible_count, discount) values (167, 52, 'Carolina Campylopus Moss', 2028.37, 19, 15);
insert into product (product_id, categoryprod_id, name, price, availible_count, discount) values (168, 69, 'Plumeweed', 2655.08, 99, 15);
insert into product (product_id, categoryprod_id, name, price, availible_count, discount) values (169, 104, 'Guardiola', 54.38, 79, null);
insert into product (product_id, categoryprod_id, name, price, availible_count, discount) values (170, 76, 'Whiteflower Currant', 2811.43, 74, 15);
insert into product (product_id, categoryprod_id, name, price, availible_count, discount) values (171, 43, 'Purple Milkweed', 4418.94, 89, null);
insert into product (product_id, categoryprod_id, name, price, availible_count, discount) values (172, 56, 'Osceola''s Plume', 4239.96, 81, null);
insert into product (product_id, categoryprod_id, name, price, availible_count, discount) values (173, 81, 'Mountain Filmy Fern', 4821.2, 19, 15);
insert into product (product_id, categoryprod_id, name, price, availible_count, discount) values (174, 27, 'Bryum Moss', 1409.72, 17, null);
insert into product (product_id, categoryprod_id, name, price, availible_count, discount) values (175, 10, 'Trans-pecos Croton', 3790.32, 78, null);
insert into product (product_id, categoryprod_id, name, price, availible_count, discount) values (176, 81, 'False Daisyleaf Moonwort', 3370.49, 53, null);
insert into product (product_id, categoryprod_id, name, price, availible_count, discount) values (177, 91, 'Willow Dock', 2235.13, 55, null);
insert into product (product_id, categoryprod_id, name, price, availible_count, discount) values (178, 38, 'Narrowleaf Colicwood', 1768.29, 59, 15);
insert into product (product_id, categoryprod_id, name, price, availible_count, discount) values (179, 23, 'Hooker''s Townsend Daisy', 4735.96, 91, 15);
insert into product (product_id, categoryprod_id, name, price, availible_count, discount) values (180, 13, 'Cleftleaf Wildheliotrope', 2684.94, 39, null);
insert into product (product_id, categoryprod_id, name, price, availible_count, discount) values (181, 16, 'Maidencane', 1889.93, 5, null);
insert into product (product_id, categoryprod_id, name, price, availible_count, discount) values (182, 51, 'Santa Lucia Dwarf Rush', 3309.96, 4, 15);
insert into product (product_id, categoryprod_id, name, price, availible_count, discount) values (183, 108, 'Bahia Piassaba Palm', 1436.2, 91, 15);
insert into product (product_id, categoryprod_id, name, price, availible_count, discount) values (184, 67, 'Wire Sedge', 1895.1, 48, null);
insert into product (product_id, categoryprod_id, name, price, availible_count, discount) values (185, 50, 'Lanai Islandmint', 3637.14, 97, null);
insert into product (product_id, categoryprod_id, name, price, availible_count, discount) values (186, 33, 'Escoba Parada', 4421.13, 68, null);
insert into product (product_id, categoryprod_id, name, price, availible_count, discount) values (187, 52, 'Coast Range Linanthus', 570.88, 25, null);
insert into product (product_id, categoryprod_id, name, price, availible_count, discount) values (188, 32, 'Mycocalicium Lichen', 582.0, 12, null);
insert into product (product_id, categoryprod_id, name, price, availible_count, discount) values (189, 59, 'Lesser Creeping Rush', 2699.23, 68, null);
insert into product (product_id, categoryprod_id, name, price, availible_count, discount) values (190, 41, 'Hybrid Oak', 4779.59, 90, null);
insert into product (product_id, categoryprod_id, name, price, availible_count, discount) values (191, 105, 'Poorjoe', 4927.53, 86, null);
insert into product (product_id, categoryprod_id, name, price, availible_count, discount) values (192, 69, 'Grand Canyon Campion', 2269.98, 77, null);
insert into product (product_id, categoryprod_id, name, price, availible_count, discount) values (193, 76, 'Indian Blanket', 4582.97, 77, null);
insert into product (product_id, categoryprod_id, name, price, availible_count, discount) values (194, 103, 'Red Hickory', 198.14, 3, 15);
insert into product (product_id, categoryprod_id, name, price, availible_count, discount) values (195, 99, 'Lacebark', 595.59, 15, null);
insert into product (product_id, categoryprod_id, name, price, availible_count, discount) values (196, 74, 'Mangrove', 3623.73, 9, 15);
insert into product (product_id, categoryprod_id, name, price, availible_count, discount) values (197, 66, 'White Moneywort', 4582.54, 12, 15);
insert into product (product_id, categoryprod_id, name, price, availible_count, discount) values (198, 104, 'Plaitleaf Dewberry', 377.19, 56, null);
insert into product (product_id, categoryprod_id, name, price, availible_count, discount) values (199, 48, 'Cup Lichen', 3452.68, 37, 15);
insert into product (product_id, categoryprod_id, name, price, availible_count, discount) values (200, 95, 'Cambustera De Costa', 1117.86, 8, 15);
insert into product (product_id, categoryprod_id, name, price, availible_count, discount) values (201, 35, 'Jewels Of Opar', 830.78, 69, null);
insert into product (product_id, categoryprod_id, name, price, availible_count, discount) values (202, 38, 'Western Blue Virginsbower', 1712.61, 34, 15);
insert into product (product_id, categoryprod_id, name, price, availible_count, discount) values (203, 44, 'Chocolate Vine', 1759.93, 23, null);
insert into product (product_id, categoryprod_id, name, price, availible_count, discount) values (204, 19, 'Sassafras', 4353.13, 11, null);
insert into product (product_id, categoryprod_id, name, price, availible_count, discount) values (205, 56, 'Mourning Buckwheat', 4682.43, 37, null);
insert into product (product_id, categoryprod_id, name, price, availible_count, discount) values (206, 44, 'Peach Thorn', 4856.83, 86, null);
insert into product (product_id, categoryprod_id, name, price, availible_count, discount) values (207, 79, 'Parish''s Oxytheca', 3170.52, 85, 15);
insert into product (product_id, categoryprod_id, name, price, availible_count, discount) values (208, 24, 'Campanilla Amarilla', 4641.77, 16, null);
insert into product (product_id, categoryprod_id, name, price, availible_count, discount) values (209, 104, 'Siberian Candle Snuffer Moss', 3857.78, 29, null);
insert into product (product_id, categoryprod_id, name, price, availible_count, discount) values (210, 108, 'Yellow Troutlily', 564.0, 28, null);
insert into product (product_id, categoryprod_id, name, price, availible_count, discount) values (211, 29, 'Summer Grape', 2411.88, 66, null);
insert into product (product_id, categoryprod_id, name, price, availible_count, discount) values (212, 21, 'Dirinaria Lichen', 1679.92, 34, null);
insert into product (product_id, categoryprod_id, name, price, availible_count, discount) values (213, 78, 'Yellow Monardella', 173.0, 26, null);
insert into product (product_id, categoryprod_id, name, price, availible_count, discount) values (214, 34, 'Black Medick', 1958.74, 5, null);
insert into product (product_id, categoryprod_id, name, price, availible_count, discount) values (215, 87, 'Waltham Creek Clarkia', 4421.53, 96, null);
insert into product (product_id, categoryprod_id, name, price, availible_count, discount) values (216, 22, 'Dodge''s Anema Lichen', 4149.05, 68, null);
insert into product (product_id, categoryprod_id, name, price, availible_count, discount) values (217, 32, 'Eastern Gamagrass', 2816.35, 40, null);
insert into product (product_id, categoryprod_id, name, price, availible_count, discount) values (218, 57, 'Grove Bluegrass', 1877.19, 41, null);
insert into product (product_id, categoryprod_id, name, price, availible_count, discount) values (219, 44, 'Arctic Wart Lichen', 2838.67, 21, 15);
insert into product (product_id, categoryprod_id, name, price, availible_count, discount) values (220, 65, 'Island Blackberry', 832.87, 15, 15);
insert into product (product_id, categoryprod_id, name, price, availible_count, discount) values (221, 21, 'Star Duckweed', 2349.85, 50, 15);
insert into product (product_id, categoryprod_id, name, price, availible_count, discount) values (222, 84, 'Ridged Yellow Flax', 3972.7, 79, null);
insert into product (product_id, categoryprod_id, name, price, availible_count, discount) values (223, 29, 'Oval-leaf Spikemoss', 4903.89, 38, null);
insert into product (product_id, categoryprod_id, name, price, availible_count, discount) values (224, 43, 'Slender Dwarf Morning-glory', 3569.79, 4, null);
insert into product (product_id, categoryprod_id, name, price, availible_count, discount) values (225, 63, 'Mann''s Cucumeropsis', 2959.33, 68, 15);
insert into product (product_id, categoryprod_id, name, price, availible_count, discount) values (226, 106, 'Grisebach''s Bristlegrass', 1863.95, 7, null);
insert into product (product_id, categoryprod_id, name, price, availible_count, discount) values (227, 3, 'Sierra Larkspur', 1526.6, 86, 15);
insert into product (product_id, categoryprod_id, name, price, availible_count, discount) values (228, 102, 'Rhizomnium Moss', 2533.8, 46, null);
insert into product (product_id, categoryprod_id, name, price, availible_count, discount) values (229, 67, 'Largeflower Yellow False Foxglove', 3642.78, 60, null);
insert into product (product_id, categoryprod_id, name, price, availible_count, discount) values (230, 101, 'Hyssopleaf Fleabane', 411.03, 34, 15);
insert into product (product_id, categoryprod_id, name, price, availible_count, discount) values (231, 98, 'Sweetpotato', 4095.38, 98, null);
insert into product (product_id, categoryprod_id, name, price, availible_count, discount) values (232, 87, 'Parry''s Sandmat', 2203.21, 44, null);
insert into product (product_id, categoryprod_id, name, price, availible_count, discount) values (233, 39, 'Cochise Adder''s-mouth Orchid', 1407.36, 76, null);
insert into product (product_id, categoryprod_id, name, price, availible_count, discount) values (234, 35, 'Turpin''s Sandmat', 2679.84, 42, null);
insert into product (product_id, categoryprod_id, name, price, availible_count, discount) values (235, 89, 'Pursh''s Rattlebox', 1545.73, 87, null);
insert into product (product_id, categoryprod_id, name, price, availible_count, discount) values (236, 5, 'Lanai Pritchardia', 4802.84, 48, null);
insert into product (product_id, categoryprod_id, name, price, availible_count, discount) values (237, 12, 'Clover''s Vervain', 1021.1, 35, null);
insert into product (product_id, categoryprod_id, name, price, availible_count, discount) values (238, 92, 'Lineleaf Fern', 1590.29, 13, null);
insert into product (product_id, categoryprod_id, name, price, availible_count, discount) values (239, 54, 'Diamond Creepingfern', 4800.19, 69, 15);
insert into product (product_id, categoryprod_id, name, price, availible_count, discount) values (240, 29, 'Honeysuckle', 1195.8, 89, null);
insert into product (product_id, categoryprod_id, name, price, availible_count, discount) values (241, 20, 'Sonoran Oak', 3951.77, 85, 15);
insert into product (product_id, categoryprod_id, name, price, availible_count, discount) values (242, 44, 'Absinthium', 4454.31, 50, null);
insert into product (product_id, categoryprod_id, name, price, availible_count, discount) values (243, 16, 'Lung Lichen', 2182.04, 90, null);
insert into product (product_id, categoryprod_id, name, price, availible_count, discount) values (244, 105, 'Afzel''s Calymperes Moss', 629.13, 28, null);
insert into product (product_id, categoryprod_id, name, price, availible_count, discount) values (245, 81, 'Narrowleaf False Dragonhead', 3004.47, 85, 15);
insert into product (product_id, categoryprod_id, name, price, availible_count, discount) values (246, 29, 'Branching Phacelia', 809.08, 87, 15);
insert into product (product_id, categoryprod_id, name, price, availible_count, discount) values (247, 97, 'White Crownbeard', 2173.98, 43, 15);
insert into product (product_id, categoryprod_id, name, price, availible_count, discount) values (248, 21, 'Oahu Clermontia', 4656.57, 96, 15);
insert into product (product_id, categoryprod_id, name, price, availible_count, discount) values (249, 3, 'Spreading Bladderpod', 3771.24, 25, null);
insert into product (product_id, categoryprod_id, name, price, availible_count, discount) values (250, 50, 'Splachnoid Dung Moss', 4379.93, 59, null);
insert into product (product_id, categoryprod_id, name, price, availible_count, discount) values (251, 43, 'Swamp Bay', 527.55, 71, 15);
insert into product (product_id, categoryprod_id, name, price, availible_count, discount) values (252, 3, 'Fuzzytongue Penstemon', 658.54, 70, null);
insert into product (product_id, categoryprod_id, name, price, availible_count, discount) values (253, 62, 'Fetid Passionflower', 2896.1, 43, 15);
insert into product (product_id, categoryprod_id, name, price, availible_count, discount) values (254, 15, 'Leiberg''s Waterlily', 811.99, 9, 15);
insert into product (product_id, categoryprod_id, name, price, availible_count, discount) values (255, 5, 'Prairie Sandreed', 2893.58, 57, null);
insert into product (product_id, categoryprod_id, name, price, availible_count, discount) values (256, 67, 'Ditch Reedgrass', 2732.97, 92, null);
insert into product (product_id, categoryprod_id, name, price, availible_count, discount) values (257, 47, 'Coast Range False Bindweed', 934.02, 28, null);
insert into product (product_id, categoryprod_id, name, price, availible_count, discount) values (258, 16, 'Scolosanthus', 1152.28, 71, 15);
insert into product (product_id, categoryprod_id, name, price, availible_count, discount) values (259, 99, 'Mimicking Sandmat', 478.99, 10, null);
insert into product (product_id, categoryprod_id, name, price, availible_count, discount) values (260, 68, 'Cylindricfruit Primrose-willow', 724.35, 76, 15);
insert into product (product_id, categoryprod_id, name, price, availible_count, discount) values (261, 50, 'Lake Almanor Clarkia', 4709.06, 49, null);
insert into product (product_id, categoryprod_id, name, price, availible_count, discount) values (262, 20, 'Small Japanese Silver Grass', 2682.52, 94, null);
insert into product (product_id, categoryprod_id, name, price, availible_count, discount) values (263, 92, 'Green Fringed Orchid', 1586.74, 5, 15);
insert into product (product_id, categoryprod_id, name, price, availible_count, discount) values (264, 26, 'Incense Cedar Mistletoe', 3475.41, 9, 15);
insert into product (product_id, categoryprod_id, name, price, availible_count, discount) values (265, 6, 'Natal Crabgrass', 2089.0, 38, null);
insert into product (product_id, categoryprod_id, name, price, availible_count, discount) values (266, 99, 'Canada Cracked Lichen', 4736.69, 77, null);
insert into product (product_id, categoryprod_id, name, price, availible_count, discount) values (267, 26, 'Leptobryum Moss', 2441.32, 51, 15);
insert into product (product_id, categoryprod_id, name, price, availible_count, discount) values (268, 25, 'Comet Grass', 4689.15, 27, 15);
insert into product (product_id, categoryprod_id, name, price, availible_count, discount) values (269, 48, 'Pacific Woodrush', 207.06, 54, 15);
insert into product (product_id, categoryprod_id, name, price, availible_count, discount) values (270, 92, 'Rough Sedge', 1548.03, 21, null);
insert into product (product_id, categoryprod_id, name, price, availible_count, discount) values (271, 2, 'Manyleaf Gilia', 3513.51, 14, null);
insert into product (product_id, categoryprod_id, name, price, availible_count, discount) values (272, 92, 'Barratt''s Sedge', 1430.5, 5, 15);
insert into product (product_id, categoryprod_id, name, price, availible_count, discount) values (273, 38, 'Dwarf Beardtongue', 47.1, 12, null);
insert into product (product_id, categoryprod_id, name, price, availible_count, discount) values (274, 4, 'Blackjack Oak', 1722.73, 46, 15);
insert into product (product_id, categoryprod_id, name, price, availible_count, discount) values (275, 8, 'Corymbia', 857.11, 67, null);
insert into product (product_id, categoryprod_id, name, price, availible_count, discount) values (276, 12, 'Williams'' Milkvetch', 828.02, 26, null);
insert into product (product_id, categoryprod_id, name, price, availible_count, discount) values (277, 60, 'Ivy', 1617.52, 1, null);
insert into product (product_id, categoryprod_id, name, price, availible_count, discount) values (278, 12, 'Nuttall''s Pleatleaf', 2300.4, 7, null);
insert into product (product_id, categoryprod_id, name, price, availible_count, discount) values (279, 36, 'Heavy Sedge', 1481.23, 36, null);
insert into product (product_id, categoryprod_id, name, price, availible_count, discount) values (280, 95, 'Narrowleaf Swordfern', 4952.58, 8, 15);
insert into product (product_id, categoryprod_id, name, price, availible_count, discount) values (281, 27, 'Cyrtandra', 139.39, 49, null);
insert into product (product_id, categoryprod_id, name, price, availible_count, discount) values (282, 92, 'Hybrid Oak', 4581.82, 27, 15);
insert into product (product_id, categoryprod_id, name, price, availible_count, discount) values (283, 37, 'Threadleaf Beaksedge', 1975.19, 86, 15);
insert into product (product_id, categoryprod_id, name, price, availible_count, discount) values (284, 2, 'Vine Jointfir', 1665.29, 21, null);
insert into product (product_id, categoryprod_id, name, price, availible_count, discount) values (285, 108, 'Nakedstem Sunray', 149.76, 88, 15);
insert into product (product_id, categoryprod_id, name, price, availible_count, discount) values (286, 105, 'Jaynes Canyon Buckwheat', 2600.56, 36, null);
insert into product (product_id, categoryprod_id, name, price, availible_count, discount) values (287, 17, 'Northern Spicebush', 1422.44, 44, null);
insert into product (product_id, categoryprod_id, name, price, availible_count, discount) values (288, 100, 'Carminatia', 3787.95, 54, null);
insert into product (product_id, categoryprod_id, name, price, availible_count, discount) values (289, 21, 'Whitebark Raspberry', 4160.87, 1, null);
insert into product (product_id, categoryprod_id, name, price, availible_count, discount) values (290, 35, 'Roundleaf Sundew', 744.88, 71, null);
insert into product (product_id, categoryprod_id, name, price, availible_count, discount) values (291, 82, 'Spring Cinquefoil', 1525.4, 30, null);
insert into product (product_id, categoryprod_id, name, price, availible_count, discount) values (292, 49, 'Winged Dock', 455.56, 13, 15);
insert into product (product_id, categoryprod_id, name, price, availible_count, discount) values (293, 43, 'Bristly Buttercup', 255.06, 47, 15);
insert into product (product_id, categoryprod_id, name, price, availible_count, discount) values (294, 57, 'Desert Pepperweed', 562.91, 67, 15);
insert into product (product_id, categoryprod_id, name, price, availible_count, discount) values (295, 85, 'Whiteheart', 3062.58, 57, 15);
insert into product (product_id, categoryprod_id, name, price, availible_count, discount) values (296, 53, 'Porter Brome', 4506.4, 65, 15);
insert into product (product_id, categoryprod_id, name, price, availible_count, discount) values (297, 21, 'Slender Parsley Piert', 1321.07, 77, 15);
insert into product (product_id, categoryprod_id, name, price, availible_count, discount) values (298, 52, 'Scabland Fleabane', 1805.97, 36, null);
insert into product (product_id, categoryprod_id, name, price, availible_count, discount) values (299, 37, 'Rim Lichen', 1363.52, 18, null);
insert into product (product_id, categoryprod_id, name, price, availible_count, discount) values (300, 35, 'Vinagre', 3165.73, 57, null);
insert into product (product_id, categoryprod_id, name, price, availible_count, discount) values (301, 5, 'Manyflowered Monkeyflower', 2055.79, 34, null);
insert into product (product_id, categoryprod_id, name, price, availible_count, discount) values (302, 104, 'Hayun Lagu', 1334.08, 97, 15);
insert into product (product_id, categoryprod_id, name, price, availible_count, discount) values (303, 105, 'Cedros Island Oak', 1937.82, 53, null);
insert into product (product_id, categoryprod_id, name, price, availible_count, discount) values (304, 59, 'Flagstaff Ragwort', 3929.58, 17, 15);
insert into product (product_id, categoryprod_id, name, price, availible_count, discount) values (305, 92, 'Gulf Vervain', 1992.49, 40, null);
insert into product (product_id, categoryprod_id, name, price, availible_count, discount) values (306, 32, 'Grand Fir', 322.45, 15, null);
insert into product (product_id, categoryprod_id, name, price, availible_count, discount) values (307, 42, 'Saskatoon Serviceberry', 4961.26, 39, 15);
insert into product (product_id, categoryprod_id, name, price, availible_count, discount) values (308, 27, 'Haleakala Cyanea', 1056.78, 70, null);
insert into product (product_id, categoryprod_id, name, price, availible_count, discount) values (309, 93, 'Cynodontium Moss', 3096.28, 2, null);
insert into product (product_id, categoryprod_id, name, price, availible_count, discount) values (310, 7, 'Sulphur Clover', 3314.25, 53, 15);
insert into product (product_id, categoryprod_id, name, price, availible_count, discount) values (311, 43, 'Lempholemma Lichen', 154.01, 37, 15);
insert into product (product_id, categoryprod_id, name, price, availible_count, discount) values (312, 92, 'Moss Campion', 2955.9, 60, null);
insert into product (product_id, categoryprod_id, name, price, availible_count, discount) values (313, 64, 'Aguinaldo Blanco', 4126.9, 1, null);
insert into product (product_id, categoryprod_id, name, price, availible_count, discount) values (314, 51, 'Chapman''s Senna', 44.41, 16, null);
insert into product (product_id, categoryprod_id, name, price, availible_count, discount) values (315, 50, 'Mountain Silverbell', 469.71, 29, null);
insert into product (product_id, categoryprod_id, name, price, availible_count, discount) values (316, 104, 'Point Reyes Ceanothus', 1947.78, 38, null);
insert into product (product_id, categoryprod_id, name, price, availible_count, discount) values (317, 5, 'Chamisso Arnica', 2951.88, 32, null);
insert into product (product_id, categoryprod_id, name, price, availible_count, discount) values (318, 38, 'Ross'' Sedge', 397.94, 11, null);
insert into product (product_id, categoryprod_id, name, price, availible_count, discount) values (319, 88, 'San Luis Obispo Wallflower', 4805.67, 90, 15);
insert into product (product_id, categoryprod_id, name, price, availible_count, discount) values (320, 44, 'San Pedro False Prairie-clover', 3194.36, 92, 15);
insert into product (product_id, categoryprod_id, name, price, availible_count, discount) values (321, 60, 'Island Tonguefern', 1763.53, 39, null);
insert into product (product_id, categoryprod_id, name, price, availible_count, discount) values (322, 74, 'Perennial Goldfields', 87.02, 1, null);
insert into product (product_id, categoryprod_id, name, price, availible_count, discount) values (323, 30, 'Small''s Yelloweyed Grass', 548.81, 58, null);
insert into product (product_id, categoryprod_id, name, price, availible_count, discount) values (324, 79, 'Panguitch Buckwheat', 228.37, 22, null);
insert into product (product_id, categoryprod_id, name, price, availible_count, discount) values (325, 27, 'Florida Yellowcress', 1621.01, 32, null);
insert into product (product_id, categoryprod_id, name, price, availible_count, discount) values (326, 18, 'Honolulu Cyanea', 474.07, 16, null);
insert into product (product_id, categoryprod_id, name, price, availible_count, discount) values (327, 27, 'Georgia Frostweed', 113.58, 91, null);
insert into product (product_id, categoryprod_id, name, price, availible_count, discount) values (328, 95, 'Hybrid Violet', 2054.62, 78, 15);
insert into product (product_id, categoryprod_id, name, price, availible_count, discount) values (329, 27, 'Hooked Pincushionplant', 1005.32, 92, null);
insert into product (product_id, categoryprod_id, name, price, availible_count, discount) values (330, 7, 'Sweet Four O''clock', 4787.21, 25, 15);
insert into product (product_id, categoryprod_id, name, price, availible_count, discount) values (331, 85, 'Panicledleaf Ticktrefoil', 99.84, 47, null);
insert into product (product_id, categoryprod_id, name, price, availible_count, discount) values (332, 108, 'Cup Lichen', 4784.7, 85, 15);
insert into product (product_id, categoryprod_id, name, price, availible_count, discount) values (333, 109, 'Ortegon', 4714.14, 86, null);
insert into product (product_id, categoryprod_id, name, price, availible_count, discount) values (334, 77, 'Pincushion Grass', 3149.56, 4, null);
insert into product (product_id, categoryprod_id, name, price, availible_count, discount) values (335, 95, 'Palmer''s Breadroot', 575.18, 80, null);
insert into product (product_id, categoryprod_id, name, price, availible_count, discount) values (336, 54, 'Canada Toadflax', 3116.51, 69, null);
insert into product (product_id, categoryprod_id, name, price, availible_count, discount) values (337, 38, 'Sierra Fringed Gentian', 4336.46, 98, null);
insert into product (product_id, categoryprod_id, name, price, availible_count, discount) values (338, 73, 'Lavender Scallops', 3875.51, 30, 15);
insert into product (product_id, categoryprod_id, name, price, availible_count, discount) values (339, 73, 'Orange Lichen', 3117.55, 50, null);
insert into product (product_id, categoryprod_id, name, price, availible_count, discount) values (340, 9, 'Quaking Aspen', 3597.97, 27, null);
insert into product (product_id, categoryprod_id, name, price, availible_count, discount) values (341, 53, 'California Figwort', 3243.81, 27, 15);
insert into product (product_id, categoryprod_id, name, price, availible_count, discount) values (342, 28, 'Arrowhead Vine', 466.13, 62, null);
insert into product (product_id, categoryprod_id, name, price, availible_count, discount) values (343, 73, 'Threetooth Horkelia', 4717.3, 86, null);
insert into product (product_id, categoryprod_id, name, price, availible_count, discount) values (344, 65, 'Rose Meadowsweet', 582.0, 71, null);
insert into product (product_id, categoryprod_id, name, price, availible_count, discount) values (345, 51, 'Boom''s Quillwort', 2660.07, 65, null);
insert into product (product_id, categoryprod_id, name, price, availible_count, discount) values (346, 35, 'Golden Linanthus', 234.88, 72, 15);
insert into product (product_id, categoryprod_id, name, price, availible_count, discount) values (347, 66, 'Zahlbrucknerella Lichen', 2913.2, 77, 15);
insert into product (product_id, categoryprod_id, name, price, availible_count, discount) values (348, 51, 'Squirreltail', 2579.92, 25, null);
insert into product (product_id, categoryprod_id, name, price, availible_count, discount) values (349, 5, 'Sand Palafox', 1384.92, 66, null);
insert into product (product_id, categoryprod_id, name, price, availible_count, discount) values (350, 76, 'Wishbone Flower', 4604.58, 30, 15);
insert into product (product_id, categoryprod_id, name, price, availible_count, discount) values (351, 64, 'Goosefoot Violet', 2656.48, 18, null);
insert into product (product_id, categoryprod_id, name, price, availible_count, discount) values (352, 51, 'Weak Saxifrage', 3712.34, 53, null);
insert into product (product_id, categoryprod_id, name, price, availible_count, discount) values (353, 94, 'Schwalbea', 3743.32, 70, null);
insert into product (product_id, categoryprod_id, name, price, availible_count, discount) values (354, 72, 'Black Mampoo', 4381.24, 29, 15);
insert into product (product_id, categoryprod_id, name, price, availible_count, discount) values (355, 12, 'African Rosemallow', 563.81, 17, null);
insert into product (product_id, categoryprod_id, name, price, availible_count, discount) values (356, 1, 'Tree Climacium Moss', 634.05, 35, null);
insert into product (product_id, categoryprod_id, name, price, availible_count, discount) values (357, 108, 'Cushion Buckwheat', 2803.73, 35, null);
insert into product (product_id, categoryprod_id, name, price, availible_count, discount) values (358, 51, 'Panamint Liveforever', 1680.19, 73, null);
insert into product (product_id, categoryprod_id, name, price, availible_count, discount) values (359, 62, 'Brittled Gum', 2259.28, 88, null);
insert into product (product_id, categoryprod_id, name, price, availible_count, discount) values (360, 96, 'Delosperma', 3007.91, 7, null);
insert into product (product_id, categoryprod_id, name, price, availible_count, discount) values (361, 74, 'Waxberry', 109.85, 58, null);
insert into product (product_id, categoryprod_id, name, price, availible_count, discount) values (362, 46, 'Polymeridium Lichen', 2050.21, 97, null);
insert into product (product_id, categoryprod_id, name, price, availible_count, discount) values (363, 63, 'Pinoche Creek Larkspur', 2364.51, 17, 15);
insert into product (product_id, categoryprod_id, name, price, availible_count, discount) values (364, 31, 'Alkali Goldenbush', 72.75, 53, 15);
insert into product (product_id, categoryprod_id, name, price, availible_count, discount) values (365, 57, 'Western Trailing Ticktrefoil', 4944.52, 87, null);
insert into product (product_id, categoryprod_id, name, price, availible_count, discount) values (366, 25, 'Stiff Yellow Flax', 3411.61, 70, null);
insert into product (product_id, categoryprod_id, name, price, availible_count, discount) values (367, 14, 'Long Pricklyhead Poppy', 223.15, 57, null);
insert into product (product_id, categoryprod_id, name, price, availible_count, discount) values (368, 58, 'Beaked Agrimony', 116.78, 9, null);
insert into product (product_id, categoryprod_id, name, price, availible_count, discount) values (369, 26, 'Sawtooth Lewisia', 3198.92, 81, null);
insert into product (product_id, categoryprod_id, name, price, availible_count, discount) values (370, 95, 'Maxon''s Goldback Fern', 3418.56, 56, 15);
insert into product (product_id, categoryprod_id, name, price, availible_count, discount) values (371, 86, 'Velvetbells', 2629.47, 5, null);
insert into product (product_id, categoryprod_id, name, price, availible_count, discount) values (372, 78, 'Payson''s Beardtongue', 1231.96, 12, null);
insert into product (product_id, categoryprod_id, name, price, availible_count, discount) values (373, 27, 'Castilla', 93.62, 86, 15);
insert into product (product_id, categoryprod_id, name, price, availible_count, discount) values (374, 37, 'Arctic Funaria Moss', 4477.73, 59, 15);
insert into product (product_id, categoryprod_id, name, price, availible_count, discount) values (375, 94, 'Carite Babyboot Orchid', 3828.15, 40, null);
insert into product (product_id, categoryprod_id, name, price, availible_count, discount) values (376, 65, 'Sandyfield Dewberry', 4732.15, 96, null);
insert into product (product_id, categoryprod_id, name, price, availible_count, discount) values (377, 61, 'Braun''s Spikemoss', 1070.62, 97, null);
insert into product (product_id, categoryprod_id, name, price, availible_count, discount) values (378, 8, 'Fiveleaf Cinquefoil', 2534.02, 12, null);
insert into product (product_id, categoryprod_id, name, price, availible_count, discount) values (379, 64, 'Stolon Stonecrop', 2962.61, 24, 15);
insert into product (product_id, categoryprod_id, name, price, availible_count, discount) values (380, 30, 'Branched Pencil Cholla', 1855.07, 76, null);
insert into product (product_id, categoryprod_id, name, price, availible_count, discount) values (381, 41, 'Waxyleaf Meadow-rue', 4706.57, 10, null);
insert into product (product_id, categoryprod_id, name, price, availible_count, discount) values (382, 44, 'Forsteronia', 3844.56, 13, null);
insert into product (product_id, categoryprod_id, name, price, availible_count, discount) values (383, 86, 'Grant''s Splendid Woodland-gilia', 3276.59, 44, null);
insert into product (product_id, categoryprod_id, name, price, availible_count, discount) values (384, 29, 'Protoparmelia Lichen', 4959.57, 98, null);
insert into product (product_id, categoryprod_id, name, price, availible_count, discount) values (385, 79, 'Giant Miscanthus', 541.04, 37, null);
insert into product (product_id, categoryprod_id, name, price, availible_count, discount) values (386, 77, 'Broadfruit Horned Beaksedge', 4901.34, 69, null);
insert into product (product_id, categoryprod_id, name, price, availible_count, discount) values (387, 41, 'Navajo Pincushion Cactus', 3816.41, 82, null);
insert into product (product_id, categoryprod_id, name, price, availible_count, discount) values (388, 79, 'Longflower Threadplant', 3786.69, 31, null);
insert into product (product_id, categoryprod_id, name, price, availible_count, discount) values (389, 86, 'Don Quixote''s Lace', 3704.95, 5, 15);
insert into product (product_id, categoryprod_id, name, price, availible_count, discount) values (390, 36, 'Adansonia', 2512.19, 6, null);
insert into product (product_id, categoryprod_id, name, price, availible_count, discount) values (391, 103, 'Petrea', 2658.36, 38, null);
insert into product (product_id, categoryprod_id, name, price, availible_count, discount) values (392, 55, 'California Manyseed', 1815.42, 47, 15);
insert into product (product_id, categoryprod_id, name, price, availible_count, discount) values (393, 53, 'Cronquist''s Blazingstar', 3443.73, 22, 15);
insert into product (product_id, categoryprod_id, name, price, availible_count, discount) values (394, 10, 'Lindbergia Moss', 4129.18, 14, null);
insert into product (product_id, categoryprod_id, name, price, availible_count, discount) values (395, 38, 'Dotted Bristle Fern', 1794.94, 58, null);
insert into product (product_id, categoryprod_id, name, price, availible_count, discount) values (396, 103, 'Rough Coneflower', 682.79, 18, 15);
insert into product (product_id, categoryprod_id, name, price, availible_count, discount) values (397, 33, 'Divided Rockcress', 1223.02, 87, null);
insert into product (product_id, categoryprod_id, name, price, availible_count, discount) values (398, 31, 'Narrowleaf Blue Eyed Mary', 227.07, 22, 15);
insert into product (product_id, categoryprod_id, name, price, availible_count, discount) values (399, 12, 'White Fawnlily', 1775.95, 91, 15);
insert into product (product_id, categoryprod_id, name, price, availible_count, discount) values (400, 109, 'Carolina Springbeauty', 4693.98, 23, 15);
insert into product (product_id, categoryprod_id, name, price, availible_count, discount) values (401, 41, 'Bulrush', 2629.5, 73, null);
insert into product (product_id, categoryprod_id, name, price, availible_count, discount) values (402, 57, 'Wenatchee Valerian', 3131.12, 4, 15);
insert into product (product_id, categoryprod_id, name, price, availible_count, discount) values (403, 18, 'Warnock''s Water-willow', 368.63, 50, null);
insert into product (product_id, categoryprod_id, name, price, availible_count, discount) values (404, 73, 'Closed Bottle Gentian', 2685.57, 40, 15);
insert into product (product_id, categoryprod_id, name, price, availible_count, discount) values (405, 8, 'Moss Campion', 1197.3, 24, null);
insert into product (product_id, categoryprod_id, name, price, availible_count, discount) values (406, 105, 'Soot Lichen', 2156.19, 66, null);
insert into product (product_id, categoryprod_id, name, price, availible_count, discount) values (407, 35, 'Hybrid Violet', 3808.34, 93, 15);
insert into product (product_id, categoryprod_id, name, price, availible_count, discount) values (408, 36, 'Rustyhair Saxifrage', 1635.13, 84, null);
insert into product (product_id, categoryprod_id, name, price, availible_count, discount) values (409, 80, 'Valley Schiedea', 3425.52, 11, null);
insert into product (product_id, categoryprod_id, name, price, availible_count, discount) values (410, 28, 'Oregon Western Rosinweed', 54.27, 75, null);
insert into product (product_id, categoryprod_id, name, price, availible_count, discount) values (411, 74, 'Sharpleaf Penstemon', 4426.28, 96, null);
insert into product (product_id, categoryprod_id, name, price, availible_count, discount) values (412, 67, 'Riverhemp', 2727.7, 55, null);
insert into product (product_id, categoryprod_id, name, price, availible_count, discount) values (413, 5, 'Bigelow''s Tansyaster', 2723.95, 49, null);
insert into product (product_id, categoryprod_id, name, price, availible_count, discount) values (414, 56, 'Red Elder', 1697.41, 73, null);
insert into product (product_id, categoryprod_id, name, price, availible_count, discount) values (415, 48, 'Boccone''s Clover', 3611.39, 61, null);
insert into product (product_id, categoryprod_id, name, price, availible_count, discount) values (416, 100, 'Huachuca Mountain Adder''s-mouth Orchid', 2197.89, 94, null);
insert into product (product_id, categoryprod_id, name, price, availible_count, discount) values (417, 25, 'Ducksbill Lousewort', 4281.27, 55, 15);
insert into product (product_id, categoryprod_id, name, price, availible_count, discount) values (418, 15, 'Longflower Tobacco', 679.36, 38, null);
insert into product (product_id, categoryprod_id, name, price, availible_count, discount) values (419, 28, 'Desert Hopbush', 733.39, 66, null);
insert into product (product_id, categoryprod_id, name, price, availible_count, discount) values (420, 88, 'Labrador Lecidea Lichen', 1535.06, 16, 15);
insert into product (product_id, categoryprod_id, name, price, availible_count, discount) values (421, 38, 'Northern Woodrush', 894.79, 33, null);
insert into product (product_id, categoryprod_id, name, price, availible_count, discount) values (422, 13, 'Turpentine Wavewing', 3312.42, 77, null);
insert into product (product_id, categoryprod_id, name, price, availible_count, discount) values (423, 106, 'Chamaecytisus', 4670.16, 76, 15);
insert into product (product_id, categoryprod_id, name, price, availible_count, discount) values (424, 26, 'Scribble Lichen', 27.74, 23, null);
insert into product (product_id, categoryprod_id, name, price, availible_count, discount) values (425, 69, 'San Francisco Spineflower', 4468.11, 71, null);
insert into product (product_id, categoryprod_id, name, price, availible_count, discount) values (426, 8, 'Eightpetal Mountain-avens', 4417.26, 26, null);
insert into product (product_id, categoryprod_id, name, price, availible_count, discount) values (427, 22, 'Mountainbay', 3556.41, 51, null);
insert into product (product_id, categoryprod_id, name, price, availible_count, discount) values (428, 65, 'Macawflower', 2515.66, 99, 15);
insert into product (product_id, categoryprod_id, name, price, availible_count, discount) values (429, 100, 'Parish''s Poppy', 726.16, 76, 15);
insert into product (product_id, categoryprod_id, name, price, availible_count, discount) values (430, 40, 'Western Tansymustard', 3601.72, 67, null);
insert into product (product_id, categoryprod_id, name, price, availible_count, discount) values (431, 89, 'Hispid Campylium Moss', 4102.71, 18, null);
insert into product (product_id, categoryprod_id, name, price, availible_count, discount) values (432, 63, 'Opium Poppy', 1206.89, 1, null);
insert into product (product_id, categoryprod_id, name, price, availible_count, discount) values (433, 83, 'Alaskan Douglasia', 2996.48, 13, 15);
insert into product (product_id, categoryprod_id, name, price, availible_count, discount) values (434, 92, 'Confederate Hawthorn', 4671.56, 77, null);
insert into product (product_id, categoryprod_id, name, price, availible_count, discount) values (435, 97, 'Powell''s Amaranth', 3871.27, 30, null);
insert into product (product_id, categoryprod_id, name, price, availible_count, discount) values (436, 109, 'Small''s Milkpea', 4931.73, 71, null);
insert into product (product_id, categoryprod_id, name, price, availible_count, discount) values (437, 35, 'Satinleaf', 2619.2, 62, null);
insert into product (product_id, categoryprod_id, name, price, availible_count, discount) values (438, 37, 'Washington Beardtongue', 3741.95, 95, 15);
insert into product (product_id, categoryprod_id, name, price, availible_count, discount) values (439, 52, 'Norwegian Cinquefoil', 890.96, 29, null);
insert into product (product_id, categoryprod_id, name, price, availible_count, discount) values (440, 92, 'Harbinger Of Spring', 4595.54, 29, 15);
insert into product (product_id, categoryprod_id, name, price, availible_count, discount) values (441, 76, 'Thistle Cholla', 4714.44, 10, null);
insert into product (product_id, categoryprod_id, name, price, availible_count, discount) values (442, 84, 'Rutter''s False Goldenaster', 3843.72, 50, null);
insert into product (product_id, categoryprod_id, name, price, availible_count, discount) values (443, 41, 'Catillaria Lichen', 4397.45, 18, 15);
insert into product (product_id, categoryprod_id, name, price, availible_count, discount) values (444, 90, 'Meadow Horsetail', 3559.25, 66, null);
insert into product (product_id, categoryprod_id, name, price, availible_count, discount) values (445, 100, 'Common Madia', 1834.1, 20, 15);
insert into product (product_id, categoryprod_id, name, price, availible_count, discount) values (446, 2, 'Pricklyleaf', 3184.02, 46, 15);
insert into product (product_id, categoryprod_id, name, price, availible_count, discount) values (447, 45, 'Hyssopleaf Hedgenettle', 1526.79, 75, null);
insert into product (product_id, categoryprod_id, name, price, availible_count, discount) values (448, 5, 'White Marsh Marigold', 1744.26, 58, 15);
insert into product (product_id, categoryprod_id, name, price, availible_count, discount) values (449, 109, 'Sphagnum', 4536.21, 4, 15);
insert into product (product_id, categoryprod_id, name, price, availible_count, discount) values (450, 69, 'False Beardgrass', 1193.49, 96, null);
insert into product (product_id, categoryprod_id, name, price, availible_count, discount) values (451, 18, 'Jones'' Townsend Daisy', 4937.32, 21, null);
insert into product (product_id, categoryprod_id, name, price, availible_count, discount) values (452, 60, 'Spleenwort', 4709.14, 23, null);
insert into product (product_id, categoryprod_id, name, price, availible_count, discount) values (453, 62, 'Boxwood', 275.71, 22, null);
insert into product (product_id, categoryprod_id, name, price, availible_count, discount) values (454, 107, 'Moa Tree', 3898.23, 69, null);
insert into product (product_id, categoryprod_id, name, price, availible_count, discount) values (455, 89, 'Sperry''s Onion', 3754.99, 98, null);
insert into product (product_id, categoryprod_id, name, price, availible_count, discount) values (456, 66, 'Witchweed', 3678.39, 58, null);
insert into product (product_id, categoryprod_id, name, price, availible_count, discount) values (457, 20, 'White Mountain Saxifrage', 2462.0, 80, null);
insert into product (product_id, categoryprod_id, name, price, availible_count, discount) values (458, 22, 'Woodland Pterostegia', 4778.53, 23, null);
insert into product (product_id, categoryprod_id, name, price, availible_count, discount) values (459, 23, 'Sage', 3929.09, 5, 15);
insert into product (product_id, categoryprod_id, name, price, availible_count, discount) values (460, 10, 'Wildrye', 441.64, 16, null);
insert into product (product_id, categoryprod_id, name, price, availible_count, discount) values (461, 75, 'Beach Pea', 3699.23, 51, 15);
insert into product (product_id, categoryprod_id, name, price, availible_count, discount) values (462, 29, 'Huckleberry', 907.54, 37, null);
insert into product (product_id, categoryprod_id, name, price, availible_count, discount) values (463, 100, 'Spurry', 3847.95, 28, 15);
insert into product (product_id, categoryprod_id, name, price, availible_count, discount) values (464, 92, 'Lone Pine Beardtongue', 3014.66, 35, null);
insert into product (product_id, categoryprod_id, name, price, availible_count, discount) values (465, 75, 'Widowstears', 489.51, 100, null);
insert into product (product_id, categoryprod_id, name, price, availible_count, discount) values (466, 108, 'Orthotrichum Moss', 4225.49, 93, null);
insert into product (product_id, categoryprod_id, name, price, availible_count, discount) values (467, 81, 'Bright Navarretia', 30.61, 19, 15);
insert into product (product_id, categoryprod_id, name, price, availible_count, discount) values (468, 81, 'Shasta Snakeroot', 4911.08, 28, null);
insert into product (product_id, categoryprod_id, name, price, availible_count, discount) values (469, 62, 'Hall''s Orthotrichum Moss', 4885.62, 85, 15);
insert into product (product_id, categoryprod_id, name, price, availible_count, discount) values (470, 100, 'Toothedleaf Nitrogen Moss', 1887.3, 97, 15);
insert into product (product_id, categoryprod_id, name, price, availible_count, discount) values (471, 50, 'Singlenerve Peperomia', 3074.95, 40, null);
insert into product (product_id, categoryprod_id, name, price, availible_count, discount) values (472, 103, 'Carolina Nutrush', 1324.69, 7, null);
insert into product (product_id, categoryprod_id, name, price, availible_count, discount) values (473, 88, 'Gambel Oak', 83.28, 38, null);
insert into product (product_id, categoryprod_id, name, price, availible_count, discount) values (474, 109, 'Chestnut Rush', 3699.66, 42, 15);
insert into product (product_id, categoryprod_id, name, price, availible_count, discount) values (475, 1, 'Black Mangrove', 4070.27, 56, null);
insert into product (product_id, categoryprod_id, name, price, availible_count, discount) values (476, 99, 'Wolf''s Evening Primrose', 3117.63, 46, null);
insert into product (product_id, categoryprod_id, name, price, availible_count, discount) values (477, 37, 'Lichenoconium Lichen', 4135.59, 73, null);
insert into product (product_id, categoryprod_id, name, price, availible_count, discount) values (478, 76, 'Yellow Waterlily', 165.41, 48, 15);
insert into product (product_id, categoryprod_id, name, price, availible_count, discount) values (479, 4, 'Clubhair Mariposa Lily', 1273.87, 12, null);
insert into product (product_id, categoryprod_id, name, price, availible_count, discount) values (480, 6, 'Koelreuteria', 4947.14, 74, 15);
insert into product (product_id, categoryprod_id, name, price, availible_count, discount) values (481, 27, 'Bushy Lippia', 1238.49, 95, 15);
insert into product (product_id, categoryprod_id, name, price, availible_count, discount) values (482, 1, 'Henry''s Lily', 4501.06, 62, null);
insert into product (product_id, categoryprod_id, name, price, availible_count, discount) values (483, 56, 'Schott''s Century Plant', 3202.5, 80, 15);
insert into product (product_id, categoryprod_id, name, price, availible_count, discount) values (484, 27, 'Indian Headdress', 2284.47, 74, null);
insert into product (product_id, categoryprod_id, name, price, availible_count, discount) values (485, 40, 'Forest Mirrorplant', 2109.48, 21, 15);
insert into product (product_id, categoryprod_id, name, price, availible_count, discount) values (486, 80, 'Lemmon''s Ceanothus', 3079.02, 9, 15);
insert into product (product_id, categoryprod_id, name, price, availible_count, discount) values (487, 84, 'Dwarf Nicker', 1971.39, 78, null);
insert into product (product_id, categoryprod_id, name, price, availible_count, discount) values (488, 44, 'Beach Pea', 2590.26, 12, null);
insert into product (product_id, categoryprod_id, name, price, availible_count, discount) values (489, 40, 'Scratchbush', 1565.67, 82, null);
insert into product (product_id, categoryprod_id, name, price, availible_count, discount) values (490, 19, 'Palo De Hueso', 381.55, 32, null);
insert into product (product_id, categoryprod_id, name, price, availible_count, discount) values (491, 55, 'Fleshy Hawthorn', 3148.31, 4, 15);
insert into product (product_id, categoryprod_id, name, price, availible_count, discount) values (492, 56, 'Alice Eastwood''s Fleabane', 1826.13, 97, 15);
insert into product (product_id, categoryprod_id, name, price, availible_count, discount) values (493, 109, 'Edmonton Hempnettle', 694.69, 10, null);
insert into product (product_id, categoryprod_id, name, price, availible_count, discount) values (494, 83, 'Pinkflower Hedgehog Cactus', 1399.4, 17, null);
insert into product (product_id, categoryprod_id, name, price, availible_count, discount) values (495, 13, 'Cutleaf Cyclanthera', 2057.22, 74, null);
insert into product (product_id, categoryprod_id, name, price, availible_count, discount) values (496, 37, 'Longstyle Rush', 4816.78, 81, null);
insert into product (product_id, categoryprod_id, name, price, availible_count, discount) values (497, 84, 'Needletip Trumpets', 4988.58, 50, null);
insert into product (product_id, categoryprod_id, name, price, availible_count, discount) values (498, 42, 'Hammock Shrubverbena', 3664.85, 51, null);
insert into product (product_id, categoryprod_id, name, price, availible_count, discount) values (499, 85, 'Slender Clubmoss', 3839.74, 33, null);
insert into product (product_id, categoryprod_id, name, price, availible_count, discount) values (500, 28, 'Shortspike Bluestem', 4159.13, 19, null);
